ALTER TABLE "blog" ALTER COLUMN "userId" SET NOT NULL;
ALTER TABLE "meal" ALTER COLUMN "userId" SET NOT NULL;
ALTER TABLE "meal_detail" ALTER COLUMN "mealId" SET NOT NULL;
ALTER TABLE "meal_detail" ALTER COLUMN "ingredientId" SET NOT NULL;